// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Jra-Wx2rTb-ymEBelMa4EoKXfGhEbVs',
    appId: '1:1077688200865:web:837e6d318681bb7c2b8ae0',
    messagingSenderId: '1077688200865',
    projectId: 'insurance-company-a92f1',
    authDomain: 'insurance-company-a92f1.firebaseapp.com',
    databaseURL: 'https://insurance-company-a92f1-default-rtdb.firebaseio.com',
    storageBucket: 'insurance-company-a92f1.firebasestorage.app',
    measurementId: 'G-P2L4ZK2L3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_2CXzTxKTFg8Af3_E1vNc9ux366ZCobs',
    appId: '1:1077688200865:android:d9954cd52e2c1d532b8ae0',
    messagingSenderId: '1077688200865',
    projectId: 'insurance-company-a92f1',
    databaseURL: 'https://insurance-company-a92f1-default-rtdb.firebaseio.com',
    storageBucket: 'insurance-company-a92f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWhzeEC73BGzdDGnRpTzDdpe204gZSkNo',
    appId: '1:1077688200865:ios:ad48054b0f608d592b8ae0',
    messagingSenderId: '1077688200865',
    projectId: 'insurance-company-a92f1',
    databaseURL: 'https://insurance-company-a92f1-default-rtdb.firebaseio.com',
    storageBucket: 'insurance-company-a92f1.firebasestorage.app',
    iosBundleId: 'com.example.tmChallenge',
  );
}
